Improve coding style
ARMmbed/dapjs pull request #106
Opened 2024-01-06 10:06 UTC by windowsair

Hi,

Thank you for your excellent work. I really like dapjs, but it looks like it hasn't been updated for a while, and now there are some dependencies that haven't been updated for a long time, and some dependencies that have been deprecated.

I'm currently trying to update the dependencies to the latest, but I'm not sure if I'm still accepting contributions from the community, so let's start with the coding style :D

2024-01-06 11:37 UTC, thegecko requested changes
Thanks for your PR, just a minor suggestion and recommendation to split the work.

2024-01-06 11:37 UTC, thegecko commented on src/transport/usb.ts
> +                        if (buffer !== undefined) {
This is a coding change, perhaps pop it in a separate PR?

2024-01-06 11:37 UTC, thegecko commented on src/transport/usb.ts
> +                            resolve(buffer);
```suggestion
                            resolve(buffer as Buffer);
```

 ? :)

2024-01-06 12:50 UTC, windowsair commented
Thank you for your fast review! There are indeed some changes in usb.ts that tend to be confusing, that are basically changes to adapt the new version, so for now I'll remove them. Then, according to your guidance, I have put some code -related modifications to the patch 2.

2024-01-11 13:27 UTC, windowsair commented on src/transport/usb.ts
> +                        if (buffer !== undefined) {
Done

2024-01-11 13:27 UTC, windowsair commented on src/transport/usb.ts
> +                            resolve(buffer);
Removed this

2024-01-11 14:49 UTC, thegecko commented
> ...according to your guidance, I have put some code -related modifications to the patch 2.

Thanks, can you pout it in a separate PR, so this PR is only code style changes?

2024-01-11 15:09 UTC, windowsair commented
> > ...according to your guidance, I have put some code -related modifications to the patch 2.
> 
> Thanks, can you pout it in a separate PR, so this PR is only code style changes?

Sure, I will push them later. Now this PR only has coding style commit.

2024-01-11 15:38 UTC, thegecko approved these changes

2024-01-11 15:53 UTC, merged