Fix endpoint detection
ARMmbed/dapjs pull request #77
Opened 2020-11-30 17:37 UTC by jreineckearm

PR to fix the endpoint detection for USB and WebUSB devices that have multiple endpoints behind a single device interface.
It assumes that debug communication happens over the first detected 'in' endpoint, and 'out' endpoint respectively.

2020-11-30 17:47 UTC, thegecko requested changes
Thanks for the changes, Jens.
Unfortunately, the build failed due to using `error.message`.

2020-11-30 17:47 UTC, thegecko commented on src/transport/usb.ts
> +                    reject(new Error(error.message));
```suggestion
                    reject(new Error(error));
```

2020-11-30 17:47 UTC, thegecko commented on src/transport/usb.ts
> +                    reject(new Error(error.message));
This causes the build to fail :(

2020-11-30 17:50 UTC, jreineckearm commented on src/transport/usb.ts
> +                    reject(new Error(error.message));
Reverted the change around error.message. Not having it failed in my local setup (need to double-check that one).
This shall however not block the actual fix of this PR.

2020-11-30 22:51 UTC, thegecko commented on src/transport/usb.ts
> +                    reject(new Error(error.message));
Probably a different `@types/node` version

2020-12-02 06:56 UTC, thegecko approved these changes

2020-12-02 06:56 UTC, merged